name: Beta Test Release

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to create GitHub releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: 'build --build-cache --daemon' # use the daemon here so the rest of the process is faster
          generate-job-summary: false
          gradle-home-cache-includes: |
            caches
            jdks
            notifications
            wrapper

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "build/libs/*.jar"
          fail_on_unmatched_files: true
          prerelease: true
          tag_name: "test"
          name: "Beta Release Testing ${{ env.COMMIT_SHORT_SHA }}"
          body: "Testing Pre-release"
